<?php

declare(strict_types=1);

return [
    'schema_version' => 1,
    'architecture_style' => 'modular_monolith',
    'runtime' => [
        'php_minimum' => '8.3.0',
        'database' => 'MariaDB 10.11+ / MySQL 8 compatible InnoDB',
        'rendering' => 'server_rendered_php_with_progressive_javascript',
        'production_state_driver' => 'mariadb',
    ],
    'layers' => [
        'entrypoint' => ['public/index.php'],
        'composition' => ['bootstrap/app.php'],
        'http' => ['app/Controllers'],
        'core' => ['app/Core'],
        'domain' => ['app/Modules'],
        'views' => ['resources/views'],
        'configuration' => ['config'],
        'persistence_schema' => ['database/migrations'],
    ],
    'modules' => [
        'platform' => [
            'description' => 'Ortak layout, hata ve henüz uygulanmamış modül yüzeyleri.',
            'controllers' => ['app/Controllers/ModuleController.php'],
            'domain_files' => [],
            'views' => [
                'resources/views/layout.php',
                'resources/views/errors/404.php',
                'resources/views/modules/placeholder.php',
            ],
            'routes' => ['GET /module/{slug}'],
        ],
        'identity' => [
            'description' => 'Oturum, giriş, parola sıfırlama ve kimlik bilgileri.',
            'controllers' => ['app/Controllers/AuthController.php'],
            'domain_files' => [
                'app/Modules/Auth/PasswordResetMailer.php',
                'app/Modules/Auth/PasswordResetStore.php',
            ],
            'views' => [
                'resources/views/auth/login.php',
                'resources/views/auth/forgot-password.php',
                'resources/views/auth/reset-password.php',
            ],
            'routes' => [
                'GET /login',
                'POST /login',
                'GET /forgot-password',
                'POST /forgot-password',
                'GET /password-reset/{token}',
                'POST /password-reset',
                'POST /logout',
            ],
        ],
        'dashboard' => [
            'description' => 'Kullanıcı paneli, hızlı izin özeti ve hava durumu.',
            'controllers' => ['app/Controllers/DashboardController.php'],
            'domain_files' => ['app/Modules/Weather/WeatherStore.php'],
            'views' => ['resources/views/dashboard/index.php'],
            'routes' => ['GET /'],
        ],
        'admin' => [
            'description' => 'Yetkiler, departmanlar, içe/dışa aktarma, audit ve sürümler.',
            'controllers' => ['app/Controllers/AdminController.php'],
            'domain_files' => [],
            'views' => [
                'resources/views/admin/access.php',
                'resources/views/admin/versions.php',
            ],
            'routes' => [
                'GET /admin/access',
                'GET /admin/versions',
                'GET /admin/access/users/export',
                'POST /admin/access/users/import',
                'POST /admin/access/users',
                'POST /admin/access/departments/create',
                'POST /admin/access/departments/delete',
                'POST /admin/access/departments',
            ],
        ],
        'personnel' => [
            'description' => 'Personel profili, organizasyon, kullanıcı adı ve şifre yönetimi.',
            'controllers' => ['app/Controllers/PersonnelController.php'],
            'domain_files' => ['app/Modules/Auth/PersonnelCredentialService.php'],
            'views' => ['resources/views/personnel/index.php'],
            'routes' => [
                'GET /module/personnel',
                'GET /personnel/export',
                'GET /personnel/export/xlsx',
                'POST /personnel/create',
                'POST /personnel/update',
                'POST /personnel/reset-password',
                'POST /personnel/delete',
            ],
        ],
        'leave' => [
            'description' => 'İzin talebi, onaylar, takvim, iptal ve izin defteri imzası.',
            'controllers' => ['app/Controllers/LeaveController.php'],
            'domain_files' => [
                'app/Modules/Leave/LeaveApprovalMailer.php',
                'app/Modules/Leave/LeaveStore.php',
            ],
            'views' => [
                'resources/views/leave/index.php',
                'resources/views/leave/book-signatures.php',
                'resources/views/leave/policies.php',
                'resources/views/leave/mail-confirm.php',
                'resources/views/leave/mail-result.php',
            ],
            'routes' => [
                'GET /module/leave',
                'GET /leave/book-signatures',
                'POST /leave/book-signatures/{id}/signed',
                'GET /leave/policies',
                'POST /leave/policies',
                'POST /leave/policies/departments/create',
                'POST /leave/policies/departments/assign-parent',
                'POST /leave/policies/departments/delete',
                'POST /leave/requests',
                'POST /leave/requests/{id}/requester-update',
                'POST /leave/requests/{id}/requester-cancel',
                'POST /leave/requests/{id}/request-cancellation',
                'POST /leave/requests/{id}/decision',
                'POST /leave/requests/{id}/cancel',
                'GET /leave/mail-approval/{token}/{decision}',
                'POST /leave/mail-approval/{token}/{decision}',
                'GET /leave/book-signature/{token}/{decision}',
                'POST /leave/book-signature/{token}/{decision}',
            ],
        ],
        'messaging' => [
            'description' => 'Konuşmalar, okundu bilgisi, pinleme ve geri yükleme.',
            'controllers' => ['app/Controllers/MessagesController.php'],
            'domain_files' => ['app/Modules/Messaging/MessageStore.php'],
            'views' => ['resources/views/messages/index.php'],
            'routes' => [
                'GET /module/messages',
                'GET /messages/unread-count',
                'POST /messages/send',
                'POST /messages/pins',
                'POST /messages/threads/read',
                'POST /messages/{id}/delete',
                'POST /messages/{id}/restore',
                'POST /messages/{id}/read',
            ],
        ],
        'shift' => [
            'description' => 'Shift şablonları, atamalar, tatiller ve aylık nöbet planları.',
            'controllers' => ['app/Controllers/ShiftController.php'],
            'domain_files' => ['app/Modules/Shift/ShiftStore.php'],
            'views' => ['resources/views/shift/index.php'],
            'routes' => [
                'GET /module/shift',
                'POST /shift/templates',
                'POST /shift/templates/delete',
                'POST /shift/weekend-plans',
                'POST /shift/weekend-plans/delete',
                'POST /shift/holidays',
                'POST /shift/holidays/delete',
                'POST /shift/assign',
            ],
        ],
        'procurement' => [
            'description' => 'Satın alma talebi ve talep listesi.',
            'controllers' => ['app/Controllers/ProcurementController.php'],
            'domain_files' => ['app/Modules/Procurement/ProcurementStore.php'],
            'views' => ['resources/views/procurement/index.php'],
            'routes' => [
                'GET /module/procurement',
                'POST /procurement/requests',
            ],
        ],
        'templates' => [
            'description' => 'GrapesJS rapor/mail şablonları ve test maili.',
            'controllers' => ['app/Controllers/TemplatesController.php'],
            'domain_files' => [
                'app/Modules/Templates/TemplateSanitizer.php',
                'app/Modules/Templates/TemplateStore.php',
                'app/Modules/Templates/TemplateTestMailer.php',
            ],
            'views' => ['resources/views/templates/index.php'],
            'routes' => [
                'GET /module/templates',
                'POST /templates/save',
                'POST /templates/test-mail',
            ],
        ],
        'notifications' => [
            'description' => 'Web Push yapılandırması, abonelik ve test bildirimi.',
            'controllers' => ['app/Controllers/PushController.php'],
            'domain_files' => ['app/Modules/Notifications/PushNotificationStore.php'],
            'views' => [],
            'routes' => [
                'GET /push/config',
                'POST /push/subscribe',
                'POST /push/unsubscribe',
                'POST /push/test',
            ],
        ],
    ],
    'state_documents' => [
        'user_profiles' => ['owner' => 'personnel', 'legacy_file' => 'storage/user-profiles.json'],
        'access_control' => ['owner' => 'admin', 'legacy_file' => 'storage/access-control.json'],
        'messages' => ['owner' => 'messaging', 'legacy_file' => 'storage/messages.json'],
        'leave_requests' => ['owner' => 'leave', 'legacy_file' => 'storage/leave-requests.json'],
        'leave_mail_outbox' => ['owner' => 'leave', 'legacy_file' => 'storage/leave-mail-outbox.json'],
        'leave_signature_scheduler' => ['owner' => 'leave', 'legacy_file' => 'storage/leave-book-signature-followup-scheduler.json'],
        'password_resets' => ['owner' => 'identity', 'legacy_file' => 'storage/password-resets.json'],
        'password_reset_mail_outbox' => ['owner' => 'identity', 'legacy_file' => 'storage/password-reset-mail-outbox.json'],
        'rate_limits' => ['owner' => 'identity', 'legacy_file' => 'storage/rate-limits.json'],
        'push_subscriptions' => ['owner' => 'notifications', 'legacy_file' => 'storage/push-subscriptions.json'],
        'vapid_keys' => ['owner' => 'notifications', 'legacy_file' => 'storage/vapid.json'],
        'shifts' => ['owner' => 'shift', 'legacy_file' => 'storage/shifts.json'],
        'procurement' => ['owner' => 'procurement', 'legacy_file' => 'storage/procurement.json'],
        'audit_log' => ['owner' => 'admin', 'legacy_file' => 'storage/audit-log.json'],
        'templates' => ['owner' => 'templates', 'legacy_file' => 'storage/templates.json'],
        'template_test_mail_outbox' => ['owner' => 'templates', 'legacy_file' => 'storage/template-test-mail-outbox.json'],
        'release_notes' => ['owner' => 'admin', 'legacy_file' => 'storage/release-notes.json'],
    ],
    'allowed_module_dependencies' => [
        'app/Controllers/AdminController.php' => ['Leave', 'Notifications'],
        'app/Controllers/AuthController.php' => ['Auth'],
        'app/Controllers/DashboardController.php' => ['Leave', 'Weather'],
        'app/Controllers/LeaveController.php' => ['Leave', 'Notifications'],
        'app/Controllers/MessagesController.php' => ['Messaging', 'Notifications'],
        'app/Controllers/PersonnelController.php' => ['Auth', 'Shift'],
        'app/Controllers/ProcurementController.php' => ['Procurement'],
        'app/Controllers/PushController.php' => ['Notifications'],
        'app/Controllers/ShiftController.php' => ['Shift'],
        'app/Controllers/TemplatesController.php' => ['Templates'],
        'app/Core/UserIdentityMigrationService.php' => ['Auth', 'Leave', 'Messaging', 'Notifications', 'Shift'],
        'app/Core/View.php' => ['Leave', 'Messaging'],
        'app/Modules/Leave/LeaveStore.php' => ['Shift'],
    ],
    'release_gate' => [
        'php_roots' => ['app', 'bootstrap', 'config', 'public', 'resources', 'scripts', 'tests'],
        'javascript_files' => [
            'public/assets/app.js',
            'public/assets/offline.js',
            'public/assets/pwa.js',
            'public/assets/templates-editor.js',
            'public/service-worker.js',
        ],
        'required_tests' => [
            'tests/architecture-regression.php',
            'tests/state-store-concurrency.php',
            'tests/core-store-smoke.php',
            'tests/user-identity-migration.php',
            'tests/leave-schedule-integrity.php',
            'tests/location-visibility.php',
            'tests/blue-collar-leave-access.php',
            'tests/personnel-credentials.php',
            'tests/personnel-organization-sync.php',
            'tests/i18n-regression.php',
            'tests/branding-regression.php',
            'tests/security-regression.php',
        ],
        'mariadb_tests' => [
            ['file' => 'tests/state-store-mariadb-concurrency.php', 'environment' => []],
            ['file' => 'tests/core-store-smoke.php', 'environment' => ['TEST_STATE_DRIVER' => 'mariadb']],
            ['file' => 'tests/user-identity-migration.php', 'environment' => ['TEST_STATE_DRIVER' => 'mariadb']],
            ['file' => 'tests/leave-schedule-integrity.php', 'environment' => ['TEST_STATE_DRIVER' => 'mariadb']],
        ],
    ],
];
